/// Flutter icons OIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OIcons
///      fonts:
///       - asset: fonts/OIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class OIcons {
  OIcons._();

  static const _kFontFam = 'OIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_up_down = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category_active = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friends = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData game = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gif = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_active = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData job = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marketplace = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData memories = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger_active = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_active = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_1 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reload = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_outlined = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angry = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laughing = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sad = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shocked = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
